#!/bin/python3
import math
import os
import random
import re
import sys
''' Day 25: Road to 10000
Problem: Capitalize'''
#Source Code
def solve(s):
    ans = s.split(' ')
    ans1 = (((i.capitalize() for i in ans)))
    return ' '.join(ans1)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
